name: Deploy to Render

# Disabled workflow running
on:
  workflow_dispatch:
#  push:
#    branches:
#      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Backend Deploy
        run: |
          curl -X POST ${{ secrets.RENDER_BACKEND_DEPLOY_HOOK }}

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Frontend Deploy
        run: |
          curl -X POST ${{ secrets.RENDER_FRONTEND_DEPLOY_HOOK }}
